[book]
src = "src"
title = "Swift Gate"

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
git-repository-url = "https://github.com/0x73696d616f/swift-gate-contracts"

[output.html.fold]
enable = true
